#include "lexer.h"
#include <ctype.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
static bool end(const Lexer*l){return l->position>=l->length;}static char peek(const Lexer*l){return end(l)?'\0':l->source[l->position];}static char nextc(const Lexer*l){return l->position+1>=l->length?'\0':l->source[l->position+1];}static char adv(Lexer*l){if(end(l))return '\0';char c=l->source[l->position++];if(c=='\n'){l->line++;l->column=1;l->at_line_start=true;}else l->column++;return c;}static Token tok(Lexer*l,TokenType t,size_t s,size_t ln,size_t col){Token x={t,l->source+s,l->position-s,ln,col,0,0.0};return x;}static Token err(Lexer*l,size_t s,size_t ln,size_t col){return tok(l,TOKEN_ERROR,s,ln,col);}static bool ids(char c){return isalpha((unsigned char)c)||c=='_';}static bool idp(char c){return isalnum((unsigned char)c)||c=='_';}
static TokenType kw(const char*s,size_t n){static const char*nms[]={"let","spark","mut","fn","return","serve","if","elif","else","for","in","while","break","slay","continue","skip","true","false","null","try","catch","finally","match"};static const TokenType ts[]={TOKEN_LET,TOKEN_LET,TOKEN_MUT,TOKEN_FN,TOKEN_RETURN,TOKEN_RETURN,TOKEN_IF,TOKEN_ELIF,TOKEN_ELSE,TOKEN_FOR,TOKEN_IN,TOKEN_WHILE,TOKEN_BREAK,TOKEN_BREAK,TOKEN_CONTINUE,TOKEN_CONTINUE,TOKEN_TRUE,TOKEN_FALSE,TOKEN_NULL,TOKEN_TRY,TOKEN_CATCH,TOKEN_FINALLY,TOKEN_MATCH};for(size_t i=0;i<sizeof(ts)/sizeof(ts[0]);i++)if(strlen(nms[i])==n&&!memcmp(nms[i],s,n))return ts[i];return TOKEN_IDENTIFIER;}
static Token ident(Lexer*l,size_t s,size_t ln,size_t col){while(idp(peek(l)))adv(l);return tok(l,kw(l->source+s,l->position-s),s,ln,col);}static Token number(Lexer*l,size_t s,size_t ln,size_t col){bool f=false;while(isdigit((unsigned char)peek(l)))adv(l);if(peek(l)=='.'&&isdigit((unsigned char)nextc(l))){f=true;adv(l);while(isdigit((unsigned char)peek(l)))adv(l);}Token t=tok(l,f?TOKEN_FLOAT:TOKEN_INTEGER,s,ln,col);size_t n=l->position-s;char b[128];if(n>=sizeof(b)){t.type=TOKEN_ERROR;return t;}memcpy(b,l->source+s,n);b[n]='\0';char*e=NULL;errno=0;if(f)t.float_value=strtod(b,&e);else t.integer_value=strtoll(b,&e,10);if(errno||e==b||*e)t.type=TOKEN_ERROR;return t;}
static Token stringt(Lexer*l,size_t s,size_t ln,size_t col){adv(l);while(!end(l)&&peek(l)!='"'){if(peek(l)=='\n')return err(l,s,ln,col);if(peek(l)=='\\'){adv(l);if(!end(l))adv(l);}else adv(l);}if(end(l))return err(l,s,ln,col);adv(l);return tok(l,TOKEN_STRING,s,ln,col);}
static Token punct(Lexer*l,size_t s,size_t ln,size_t col){char c=adv(l);if(c=='-'&&peek(l)=='>'){adv(l);return tok(l,TOKEN_ARROW,s,ln,col);}if((c=='='||c=='!'||c=='<'||c=='>')&&peek(l)=='='){adv(l);return tok(l,c=='='?TOKEN_EQUAL_EQUAL:c=='!'?TOKEN_BANG_EQUAL:c=='<'?TOKEN_LESS_EQUAL:TOKEN_GREATER_EQUAL,s,ln,col);}TokenType t;switch(c){case'+':t=TOKEN_PLUS;break;case'-':t=TOKEN_MINUS;break;case'*':t=TOKEN_STAR;break;case'/':t=TOKEN_SLASH;break;case'%':t=TOKEN_PERCENT;break;case'=':t=TOKEN_ASSIGN;break;case'!':t=TOKEN_BANG;break;case'<':t=TOKEN_LESS;break;case'>':t=TOKEN_GREATER;break;case'(':t=TOKEN_LEFT_PAREN;break;case')':t=TOKEN_RIGHT_PAREN;break;case'[':t=TOKEN_LEFT_BRACKET;break;case']':t=TOKEN_RIGHT_BRACKET;break;case'{':t=TOKEN_LEFT_BRACE;break;case'}':t=TOKEN_RIGHT_BRACE;break;case',':t=TOKEN_COMMA;break;case'.':t=TOKEN_DOT;break;case':':t=TOKEN_COLON;break;default:return err(l,s,ln,col);}return tok(l,t,s,ln,col);}
static Token indent(Lexer*l){size_t s=l->position,ln=l->line,col=l->column;unsigned spaces=0;while(peek(l)==' '||peek(l)=='\t')spaces+=adv(l)=='\t'?4U:1U;if(peek(l)=='#'||peek(l)=='\n'||end(l)){while(!end(l)&&peek(l)!='\n')adv(l);l->at_line_start=false;return lexer_next(l);}unsigned cur=l->indent_stack[l->indent_depth];l->at_line_start=false;if(spaces>cur){if(l->indent_depth+1>=FEM_MAX_INDENT_DEPTH)return err(l,s,ln,col);l->indent_stack[++l->indent_depth]=spaces;return tok(l,TOKEN_INDENT,s,ln,col);}if(spaces<cur){while(l->indent_depth&&spaces<l->indent_stack[l->indent_depth]){l->indent_depth--;l->pending_dedents++;}if(spaces!=l->indent_stack[l->indent_depth])return err(l,s,ln,col);if(l->pending_dedents){l->pending_dedents--;return tok(l,TOKEN_DEDENT,s,ln,col);}}return lexer_next(l);}
void lexer_init(Lexer*l,const char*s,size_t n){memset(l,0,sizeof(*l));l->source=s;l->length=n;l->line=1;l->column=1;l->at_line_start=true;}Token lexer_next(Lexer*l){if(l->pending_dedents){l->pending_dedents--;return tok(l,TOKEN_DEDENT,l->position,l->line,l->column);}if(l->at_line_start)return indent(l);while(!end(l)){char c=peek(l);if(c==' '||c=='\t'||c=='\r'){adv(l);continue;}if(c=='#'){while(!end(l)&&peek(l)!='\n')adv(l);continue;}break;}if(end(l)){if(l->indent_depth&&!l->emitted_eof){l->emitted_eof=true;l->pending_dedents=l->indent_depth;l->indent_depth=0;return lexer_next(l);}l->emitted_eof=true;return tok(l,TOKEN_EOF,l->position,l->line,l->column);}size_t s=l->position,ln=l->line,col=l->column;char c=peek(l);if(c=='\n'){adv(l);return tok(l,TOKEN_NEWLINE,s,ln,col);}if(ids(c))return ident(l,s,ln,col);if(isdigit((unsigned char)c))return number(l,s,ln,col);if(c=='"')return stringt(l,s,ln,col);return punct(l,s,ln,col);}
